name: SplitWise

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
jobs:
  test-and-build:
    name: Build App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install 

      - name: Run tests
        run: npm test 

      - name: Build app
        run: npm run build